### ISSUE TITLE
Argentina examples changes to 9

### ISSUE THREAD

**Issue by fguespe** [LouisMazel/vue-phone-number-input#42]
Hello, if you input a number like the example, the second character changes to a 9 automatically...

Try to input 011 15 or 011 11

Also i would like to change argentinian example label, is this possible?

**Comment by fguespe** [comment]
For now i have changed it to

label[for=VuePhoneNumberInput_phone_number]{/*esconde ejemplo*/
    display:none
}
#VuePhoneNumberInput_phone_number{
    padding-top:0px
}

**Comment by LouisMazel** [comment]
Hi,

I will fix this bug in the next version. The bug comes from [libphonenumber-js](https://www.npmjs.com/package/libphonenumber-js)
I updated it and it's good
I released the next version soon (0.2.7)

And to change the label, please use the `translations` attributes (cf documentation)

Thanks for your feedback

**Comment by LouisMazel** [comment]
It's fixed into `0.2.7` version

[Release 0.2.7](https://github.com/LouisMazel/vue-phone-number-input/releases/tag/0.2.7)
