### ISSUE TITLE
(BUG) This component uses the non standard property “zoom”. 

### ISSUE THREAD

**Issue by MLDMoritz** [LouisMazel/vue-phone-number-input#94]
This component uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.

https://github.com/LouisMazel/vue-phone-number-input/blob/0239ca2c7e7e83e9ef71d960097545d8670aa9c8/src/VuePhoneNumberInput/CountrySelector/index.vue#L602

https://github.com/LouisMazel/vue-phone-number-input/blob/0239ca2c7e7e83e9ef71d960097545d8670aa9c8/src/VuePhoneNumberInput/CountrySelector/index.vue#L636

**Comment by LouisMazel** [comment]
Hi @MLDMoritz,

Thanks for your feedback !

This bug it's fixed in the last version of my new library [Maz-UI (1.2.2)](https://louismazel.github.io/maz-ui/)

**MazPhoneNumberInput**: [Documentation & Demo](https://louismazel.github.io/maz-ui/#/documentation/phone-number-input)
**MAZ-UI - RELEASE 1.2.2 - Changelog**: https://github.com/LouisMazel/maz-ui/releases/tag/v1.2.2
