### ISSUE TITLE
Country selector opens select without chosen country in view

### ISSUE THREAD

**Issue by RuslanFahrenheit** [LouisMazel/vue-phone-number-input#95]
Hi. Thanks for your useful package).

I found the little bug:
Clicking the country selector with predefined country code opens select without chosen country in view. But the second opening works as expected.

## Steps to reproduce

Describe us how we could reproduce the bug you're trying to report.

Example:

 1. Go to [https://louismazel.github.io/vue-phone-number-input/](https://louismazel.github.io/vue-phone-number-input/)
 2. Click on country selector in 'Basic Usage' section.
 3. Close it and click it again.

## Expected behaviour

Chosen country is in view and highlighted after the first click.

## Screenshots

[https://prntscr.com/salsp6](https://prntscr.com/salsp6)
[https://prnt.sc/saltvr](https://prnt.sc/saltvr)

## Device

- Browser: Chrome
Haven't check on another devices and in different browsers yet.

**Comment by LouisMazel** [comment]
Hello @RuslanFahrenheit,

Thanks for your report, I will fix it. I keep you posted.

**Comment by LouisMazel** [comment]
Hi, 

The bug is fixed on the new version of this component ! 
The new version of VuePhoneNumberInput is now on my **new library** [Maz-UI](https://louismazel.github.io/maz-ui/)

See **doc/demo** page of [MazPhoneNumberInput](https://louismazel.github.io/maz-ui/#/documentation/phone-number-input)
Some options may change, check the props documentation with the top right button

In this new library, you can enjoy lot of others components in the same style. 
You can just install the component you want (and not the whole library), for this
Read the [Get started](https://louismazel.github.io/maz-ui/#/documentation/get-started) page

If you have any problem or question, do no hesitate to ask me !

**Comment by RuslanFahrenheit** [comment]
Thank you! You are the best. )

**Comment by ikasianiuk** [comment]
hey @LouisMazel, maybe you could advise any workaround for those who can't use new version of VuePhoneNumberInput component for now?
