### ISSUE TITLE
vue-phone-number-input.css contains flag image path

### ISSUE THREAD

**Issue by vipinkundal** [LouisMazel/vue-phone-number-input#97]
I used in Vue project and my build failed
`Module parse failed: Unexpected character ‘�’ (1:0)`

My webpack.config file have rules which would handle image file
   `test    : /\.(png|jpg|svg)$/,`

Then I track down that **vue-phone-number-input.css** file have 2 lines where its calling flag image path and I replaced those paths with base64 image code which resolved my issue.

Should it be in base64 by default?

**Comment by LouisMazel** [comment]
Hi, 

The bug is fixed on the new version of this component ! 
The new version of VuePhoneNumberInput is now on my **new library** [Maz-UI](https://louismazel.github.io/maz-ui/)

See **doc/demo** page of [MazPhoneNumberInput](https://louismazel.github.io/maz-ui/#/documentation/phone-number-input)
Some options may change, check the props documentation with the top right button

In this new library, you can enjoy lot of others components in the same style. 
You can just install the component you want (and not the whole library), for this
Read the [Get started](https://louismazel.github.io/maz-ui/#/documentation/get-started) page

If you have any problem or question, do no hesitate to ask me !
